import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`Tim's Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="face">
        <Image
            className={styles.face}
            src='/face.jpeg'
            alt='head-shot'
            width={300}
            height={300}
        />
      </div>
      <div className={styles.name}>

        <h1 >Timothy A Palmer</h1>
      
        <p>Full-stack Developer</p>
      </div>
      <div className={styles.skills}>
        <h3>Skills</h3>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>javaScript</li>
            <li>SQL</li>
            <li>React</li>
            <li>mongoose</li>
            <li>MongoDB</li>
            <li>React-Native</li>
            <li>django</li>
            <li>github</li>
          </ul>
      </div>
    </div>
  )
}
